apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: video-demogenai-job-dev
spec:
  template:
    spec:
      containers:
      - image: video-demogenai-job
        resources:
          limits:
            cpu: 1
            memory: 512Mi