# Cloud Deploy uses Skaffold to provide the details for what to deploy and how to deploy it properly for your separate targets.

apiVersion: skaffold/v3alpha1
kind: Config
metadata: 
  name: cloud-run-app
profiles:
- name: dev
  manifests:
    rawYaml:
    - deploy-dev.yaml
- name: pre
  manifests:
    rawYaml:
    - deploy-pre.yaml
- name: prod
  manifests:
    rawYaml:
    - deploy-prod.yaml
deploy:
  cloudrun: {}