apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: _IMAGE_NAME-dev
spec:
  template:
    spec:
      containers:
      - image: _IMAGE_NAME
        resources:
          limits:
            cpu: 1
            memory: 512Mi