apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: api-meteo-demo-dev
spec:
  template:
    spec:
      containers:
      - image: api-meteo-demo
        resources:
          limits:
            cpu: 1
            memory: 512Mi