"PROJECT_ID="vtxdemos"  \
REGION="us-central1"  \
FPS_GCS_URI="gsc_fps_gcs_video_demogenai"  \
VIDEO_TRANSCRIPT_ANNOTATIONS_GCS="gsc_video_transcript_annotationsvideo_demogenai"  \
SNIPPETS_GCS_URI="gsc_snippets_video_demogenai" \
VIDEO_GCS_URI="gsc_video_demogenai"  \
PICKLE_FILE_NAME="emb2.pkl"  \
LINUX=False  \
INSTANCE_NAME="postgresdemovideoai"  \
DATABASE_USER="emb-admin"  \
DATABASE_NAME="dbvideogenai"
"PROJECT_ID="vtxdemos" 
REGION="us-central1"
FPS_GCS_URI="gsc_fps_gcs_video_demogenai"
VIDEO_TRANSCRIPT_ANNOTATIONS_GCS="gsc_video_transcript_annotationsvideo_demogenai"
SNIPPETS_GCS_URI="gsc_snippets_video_demogenai"
VIDEO_GCS_URI="gsc_video_demogenai"  
PICKLE_FILE_NAME="emb2.pkl"  
LINUX=False
INSTANCE_NAME="postgresdemovideoai"
DATABASE_USER="emb-admin"
DATABASE_NAME="dbvideogenai"
